[workspace]
git_only = true
git_release_enable = true
git_tag_name = "v{{ version }}"
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
pr_name = "chore: release v{{ version }}"
release_always = false
release_commits = "^(feat|fix|perf|refactor)(\\(.+\\))?!?:|^(build|ci)\\((release|dist|install|deps)\\)!?:|^revert:"
repo_url = "https://github.com/runrly/zwd"
semver_check = false
features_always_increment_minor = true

[changelog]
protect_breaking_commits = true
tag_pattern = "v[0-9]*"
