name: Commit Messages

on:
  pull_request:

permissions:
  contents: read

jobs:
  committed:
    name: Conventional Commits
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: true
      - name: Check commit messages
        run: devbox run -- committed --config committed.toml --no-merge-commit "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
