name: Commit Messages

on:
  pull_request:

permissions:
  contents: read

jobs:
  committed:
    name: Conventional Commits
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Rust
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
      - name: Install committed
        run: cargo install committed --locked
      - name: Check commit messages
        run: committed --config committed.toml --no-merge-commit "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
